from typing import Protocol, Optional, List, Dict, Any

from ..core.models import User, Group, PermissionNode


class PermissionStore(Protocol):
    async def get_user(self, user_id: str) -> Optional[User]: ...
    async def save_user(self, user: User) -> None: ...
    async def delete_user(self, user_id: str) -> None: ...
    async def list_users(self) -> List[str]: ...

    async def get_group(self, name: str) -> Optional[Group]: ...
    async def save_group(self, group: Group) -> None: ...
    async def delete_group(self, name: str) -> None: ...
    async def list_groups(self) -> List[str]: ...

    async def get_registered_nodes(self) -> List[PermissionNode]: ...
    async def save_registered_node(self, node: PermissionNode) -> None: ...

    async def load_all(self) -> None: ...
    async def save_all(self) -> None: ...
